//校验的正则表达式及校验的提示字符
const validateRules = {
    "rule": {
        name: "[\x00-\xff]{6,32}$",
        text: "[\u4e00-\u9fa5]$",
        idname: "^[a-zA-Z]{1}([0-9a-zA-Z_-]){5,19}$",
        email: "^[a-z0-9._%-]+@([a-z0-9-]+\\.)+[a-z]{2,4}$",
        number: "^\\-?\\d+(\\.\\d+)?$",
        url: "^(http|https)\\:\\/\\/[a-z0-9\\-\\.]+\\.[a-z]{2,3}(:[a-z0-9]*)?\\/?([a-z0-9\\-\\._\\:\\?\\,\\'\\/\\\\\\+&amp;%\\$#\\=~])*$",
        tel: "^1\\d{10}$",
        validatedode: "^\\d{4}$",//验证码
        password: '^.{6,20}$',
        tradePassword: "^.{6,20}$",
        zipcode: "^\\d{6}$",
        date: "^\\d{4}\\-(0\\d|1[0-2])\\-([0-2]\\d|3[0-1])$",
        time: "^[0-2]\\d\\:[0-5]\\d$",
        hour: "^[0-2]\\d\\:00$",
        minute: "^[0-2]\\d\\:[0-5]\\d$",
        "date-range": "^\\d{4}(\\-\\d{2}){2}\\s至\\s\\d{4}(\\-\\d{2}){2}$",
        "month-range": "^\\d{4}\\-\\d{2}\\s至\\s\\d{4}\\-\\d{2}$",
        isNotNull: '\\S',
        idCard: /^[1-9]\d{7}((0\d)|(1[0-2]))(([0|1|2]\d)|3[0-1])\d{3}$|^[1-9]\d{5}[1-9]\d{3}((0\d)|(1[0-2]))(([0|1|2]\d)|3[0-1])\d{3}([0-9]|X)$/,
        bankCard: /^(\d{16}|\d{19})$/,
        merchantCode: "^\\d{15}$",
        paypassword: "^\\d$",
        invitationcode:"^\\d{6}$",
        largeThousand:"[1-9]\\,*\\d{3,}([\\.\\d*]*)",
        conName:"[\u4E00-\u9FA5]{2,4}",
        fixedPhone:/^((0\d{2,3})-)(\d{7,8})(-(\d{3,}))?$/,
        moneynotnull:'\\S',
        leastOne:'',
        sort:"/^[1-9][0-9]{0,1}$/"
    },
    "message": {
        name: "只能是半角的数字、字母、下划线，长度6-32个字符",
        text: "请输入中文字符",
        idname: "ID",
        email: "邮箱格式错误",
        tel: "请输入正确的手机号码",
        validatedode: '请输入短信验证码',
        url: "网址",
        zipcode: "邮编",
        password: "登录密码必须是6-20位数字、字母或符号",
        tradePassword: "交易密码必须是6-20位数字、字母或符号",
        number: "数值",
        range: "数值",
        date: "日期",
        year: "年份",
        month: "月份",
        hour: "小时",
        minute: "分钟",
        time: "时间",
        datetime: "日期时间",
        "date-range": "日期范围",
        "month-range": "月份范围",
        isNotNull: "不能为空",
        idCard: "请输入正确的身份证号码",
        bankCard: "请输入正确的银行卡号",
        merchantCode: '商户号必须为15位数字',
        invitationcode: '邀请码必须为4位数字',
        largeThousand:'起结金额应大于或等于1000元',
        conName:'请输入联系人姓名',
        fixedPhone:'请输入正确的固定电话',
        moneynotnull:'请填写起结金额',
        notNull:'不能为空值',
        sort:"请填写1-99之间的数字"
    }
}
